name: conda_env
dependencies:
  - python=3.9
  - pip
  - pip:
    - pip==21.3.1
    - torch==1.12.1
    - nltk==3.6.5
    - pandas==1.4.3
    - scikit-learn==1.1.2
    - numpy==1.23.0
    - matplotlib==3.5.2
    - seaborn==0.11.2
    - ipykernel==6.15.1
